version: '2'
services:
    backend:
      image: python:3.7
      container_name: "backend"
      working_dir: /app
      command: bash -c "pip install -r requirements.txt && gunicorn -w 4 -b 0.0.0.0:5000 backend:app"
      volumes:
        - ./:/app
      ports:
        - "5000:5000"
